### ISSUE TITLE
Makefile run problem

### ISSUE THREAD

**Issue by OmerBerk** [liman/liman#1]
Hello,
I just tried to use liman and when I run makefile it gives error as follows but manual build works fine.
This is the error:
```
gcc src/liman.c -o bin/liman
/usr/bin/ld: cannot open output file bin/liman: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

**Comment by alorak** [comment]
We found the problem. Because it is not the "bin/" folder.
